### ISSUE TITLE
failure to export multiple-synapse netConns to NeuroMLv2beta

### ISSUE THREAD

**Issue by epiasini** [NeuralEnsemble/neuroConstruct#11]
In neuroConstruct it's possible to define netConns with more than one synaptic types. When these are exported to NeuroMLv2beta, though, only the first synaptic type gets exported. For example, in my case I have the mossy fibre to granule cell connection which has an AMPA as well as NMDA component, but only the AMPA gets exported to neuroml.

For a minimal example, see https://github.com/epiasini/multiple_synapses. Just generate the default simulation configuration and export to NeuroMLv2beta. Inspect multiple_synapses.nml to see that the network connection between SampleCellGroup and SampleCellGroup_1 contains only DoubExpSyn, rather than both DoubExpSyn and DoubExpSyn_1.

**Comment by pgleeson** [comment]
This is fixed at the moment, but there are still issues with exporting connections with weights and delays. Working on it currently...

**Comment by pgleeson** [comment]
Done. See for example: https://github.com/OpenSourceBrain/GranCellLayer/blob/master/neuroConstruct/generatedNeuroML2/GranCellLayer.net.nml
