### ISSUE TITLE
NeuroMLv2 export does not support random spike train inputs

### ISSUE THREAD

**Issue by epiasini** [NeuralEnsemble/neuroConstruct#15]
See for example the default simulation configuration in [my granule cell project](https://github.com/epiasini/GranCellRothmanIf/commit/562e759397ebc507f366b7e4f8665ccee9e08b92).

**Comment by pgleeson** [comment]
This is possible at the moment. Try the Gran Cell layer project for example https://github.com/OpenSourceBrain/GranCellLayer
