### ISSUE TITLE
Issue while running ./nC.sh .

### ISSUE THREAD

**Issue by wachub** [NeuralEnsemble/neuroConstruct#57]
I am using a Ubuntu 14.10 and this is the error I get when I try to run ./nC.sh..

src/ucl/physiol/neuroconstruct/neuron/NeuronFileManager.java:59: error: package org.lemsml.jlems.core.sim does not exist
import org.lemsml.jlems.core.sim.Sim;
                                ^
src/ucl/physiol/neuroconstruct/neuron/NeuronFileManager.java:60: error: package org.lemsml.jlems.core.type does not exist
import org.lemsml.jlems.core.type.Component;
                                 ^
src/ucl/physiol/neuroconstruct/neuron/NeuronFileManager.java:61: error: package org.neuroml.export.utils does not exist
import org.neuroml.export.utils.Utils;
                               ^
src/ucl/physiol/neuroconstruct/neuron/NeuronFileManager.java:62: error: package org.neuroml.export.neuron does not exist
import org.neuroml.export.neuron.NeuronWriter;
                                ^
src/ucl/physiol/neuroconstruct/neuron/NeuronFileManager.java:63: error: package org.neuroml.export.neuron.NeuronWriter does not exist
import org.neuroml.export.neuron.NeuronWriter.ChannelConductanceOption;

**Comment by pgleeson** [comment]
Hi @wachub, are you working with the latest from GitHub?

Have you done:

    ./updatenC.sh
    << opened nCenv.sh and changed NC_HOME >>
    ./nC.sh -make
    ./nC.sh

**Comment by wachub** [comment]
Works perfectly now, thankyou.

**Comment by pgleeson** [comment]
Glad to hear it.
