### ISSUE TITLE
NeuroConstruct 1.7.2 crash 

### ISSUE THREAD

**Issue by Heidecamper** [NeuralEnsemble/neuroConstruct#63]
If I use the latest version of neuroConstruct (directly downloaded from the repository). I have the following problem. As soon as I try and visualize the latest generated positions under the header Visualisation. NeuroConstruct crashes and I get the following output in the terminal:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/mathijs/Documents/TuDelft/BEP/neuroConstruct/lib/j3d/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

If I do the same steps before visualizing the cell in a previous version of neuroConstruct everything works fine. Though version 1.7.2 has some bug-fixes which make life a lot easier so I'd rather stick to the latest version. Any ideas on how to solve this problem?

**Comment by pgleeson** [comment]
What is your OS/version? Can you mail me the output of Help-> Java & System properties from the GUI?

**Comment by Heidecamper** [comment]
Sorry for the late response, I did not have my laptop with me yesterday. Thank you for helping me out and I just mailed you the ouput!

**Comment by pgleeson** [comment]
From your logs it looks like the main difference you have from my machine (also Ubuntu 18.04) is you're using OpenJDK v11 as opposed to Oracle's Java SE Runtime Environment v1.8.0. You can switch between the versions of Java using:

    sudo update-alternatives --config java

See https://aboullaite.me/switching-between-java-versions-on-ubuntu-linux/.

It should be possible to get it to work with OpenJDK (it builds fine, it's just the pretty ancient 3D libraries I use...) but hopefully switching your version of Java should solve the issue.

**Comment by Heidecamper** [comment]
Dear Pagraig,

That was indeed the problem. Thank you for helping me out once again!

Kind regards,
Mathijs

________________________________
Van: Padraig Gleeson <notifications@github.com>
Verzonden: maandag 20 mei 2019 12:05
Aan: NeuralEnsemble/neuroConstruct
CC: Heidecamper; Author
Onderwerp: Re: [NeuralEnsemble/neuroConstruct] NeuroConstruct 1.7.2 crash (#63)


From your logs it looks like the main difference you have from my machine (also Ubuntu 18.04) is you're using OpenJDK v11 as opposed to Oracle's Java SE Runtime Environment v1.8.0. You can switch between the versions of Java using:

sudo update-alternatives --config java


See https://aboullaite.me/switching-between-java-versions-on-ubuntu-linux/.

It should be possible to get it to work with OpenJDK (it builds fine, it's just the pretty ancient 3D libraries I use...) but hopefully switching your version of Java should solve the issue.
